#ifndef _DIRECTORY_TREE_ERROR_CODE_H
#define _DIRECTORY_TREE_ERROR_CODE_H

//	0 sucess
// error range [50000,50099] 
enum DIR_TREE_ERROR_CODE
{
	DIR_TREE_OK = 0,
	DIR_TREE_PATH_TOO_DEEP = 50000,
	DIR_TREE_LOST_PARENT,
	DIR_TREE_PATH_CONFLICT,
	DIR_TREE_FILE_FOLDER_NAME_CONFLICT
};
#endif